[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
sourceDir = "."
buildCommand = "npm run build"
startCommand = "npm start"

[[services]]
name = "backend"
sourceDir = "backend"
buildCommand = "npm install"
startCommand = "npm start"

[[services]]
name = "database"
type = "postgresql"
